apiVersion: v1
kind: Service
metadata:
  name: ocr-app
spec:
  selector:
    app: ocr-app
  ports:
    - protocol: "TCP"
      port: 3000
      targetPort: 5000 # container pod
      nodePort: 32005
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-app
spec:
  selector:
    matchLabels:
      app: ocr-app
  replicas: 2
  template:
    metadata:
      labels:
        app: ocr-app
    spec:
      containers:
        - name: ocr-app
          image: namntgem/fastapi_ocr_app:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000